[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
idngenelectevotingsolana = "FRb4ZRPozZeBDrvXEKPqHDBYonp7YQg1WHF95KRKF8cA"

[programs.devnet]
idngenelectevotingsolana = "FRb4ZRPozZeBDrvXEKPqHDBYonp7YQg1WHF95KRKF8cA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
